project:
  type: book

book:
  page-footer: "![](img/Logo_Grande_DevSci_Sem_Fundo.png){width=15%} <br> DevSci Space <br>"
  title: "Guia Prático de Configuração"
  subtitle: "Introdução à Ciências de Dados" 
  author: "Bruno Oliveira"
  favicon: img/Logo_Grande_DevSci_Sem_Fundo.png
  date: "22/10/2025"
  sidebar: 
    background: "#F0F6FF"
    logo: img/capa_guia_pratico.png
    search: true
  image: img/capa_guia_pratico.png
  chapters:
    - index.qmd
    - intro.qmd
    - config_positron.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: minty
    code-fold: false
    css: custom.css
    backgroundcolor: "#F0F6FF"

editor: visual

